---
- name: test playbook
  hosts: all
  become: yes
  tasks:
   - name: install httpd 
     yum:
       name: httpd
       state: latest

   - name: check httpd is there 
     command: systemctl is-active httpd
     ignore_errors: yes

   - name: start httpd service
     service:
      name: httpd
      state: started

   - name: check httpd is there
     command: systemctl is-active httpd

